version: '3.1'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    depends_on:
      - mongo 
    
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017